### PR TITLE
Fixed main queue setup Warning

### PR DESCRIPTION
**Pull request by ironicbrew**
react-native version used: ```0.70.6```

Warning appearing on app init ```Module MetronomeModule requires main queue setup since it overrides 'init' but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of```

PR fixes this warning with the assumption MainQueueSetup is not needed.

### CODE REVIEW

**Comment by jonestristand** [comment]
This is showing only as a warning, correct? Not as an error/

**Comment by ironicbrew** [comment]
Yeah sorry I kept writing error by mistake. It's a yellow warning.

**Comment by jonestristand** [comment]
Let me look into this a bit more - it's unclear if requiresMainQueueSetup should return YES...

**Comment by ironicbrew** [comment]
```
+ (BOOL)requiresMainQueueSetup
{
  return MAYBE;
}
```

**Pull request merged**
